name: applocale
description: A Flutter plugin to enable support for internationalization (i18n) or different language with json files.
version: 0.1.1-dev+1
authors:
  - Tamal Patra <patra.tamal@gmail.com>
homepage: https://github.com/Terran-Source/applocale
repository: https://github.com/Terran-Source/applocale
issue_tracker: https://github.com/Terran-Source/applocale/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  test: ^1.14.2
